package de.hterhors.obie.core.utils;

public class ToStringFormatter {

	public static void main(String[] args) {
		String s = "Result = CResult [investigationMethod=null,judgement=null,observationTimepoint=null,referenceGroup=SReferenceGroup [experimentalGroup=CReferenceGroup [animalModel=CWistarRatModel [age=CAge [textMention=40 days],ageCategory=null,gender=CAnimalGender [textMention=male],textMention=wistarRat,weight=null],experimentalGroupNumber=null,groupName=null,groupNumber=null,injuryModel=null,nNumber=null,textMention=null,treatmentType=null],groupName=CGroupName [textMention=Pool1],groupNumber=CGroupNumber [textMention=1],textMention=someReference],referenceGroupSetup=null,targetGroup=null,targetGroupSetup=null,textMention=null,trend=null]";

		System.out.println("Formatted String = \n" + formatString(s));
	}

	/**
	 * Formats a given input String that was generated by a (autogenerated)
	 * toString-Method of a class. It returns a more readable String of the
	 * input.
	 * 
	 * @param inputString
	 * @return formatted inputString
	 */
	public static String formatString(final String inputString) {

		StringBuilder outPutString = new StringBuilder();

		int indentation = 0;
		for (char c : inputString.toCharArray()) {
			outPutString.append(c);

			if (c == ',') {
				outPutString.append('\n');
				for (int i = 0; i < indentation; i++) {
					outPutString.append('\t');
				}
			}
			if (c == ']') {
				indentation--;
			}
			if (c == '[') {

				outPutString.append('\n');
				indentation++;
				for (int i = 0; i < indentation; i++) {
					outPutString.append('\t');
				}
			}

		}

		return outPutString.toString();

	}

}
